apiVersion: apps/v1
kind: Deployment
metadata:
  name: iwas-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iwas-api
  template:
    metadata:
      labels:
        app: iwas-api
    spec:
      containers:
        - name: iwas-api
          image: elijahred23/iwas-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5050
          readinessProbe:
            httpGet:
              path: /api/ping
              port: 5050
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /api/ping
              port: 5050
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 3
          envFrom:
            - configMapRef:
                name: iwas-config
            - secretRef:
                name: iwas-secret
            - secretRef:
                name: iwas-db-secret
