apiVersion: apps/v1
kind: Deployment
metadata:
  name: iwas-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iwas-api
  template:
    metadata:
      labels:
        app: iwas-api
    spec:
      containers:
        - name: iwas-api
          image: elijahred23/chat-book-site-api:0.0.65
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: iwas-config
            - secretRef:
                name: iwas-secret
