apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iwas-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: iwas-capstone.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: iwas-api
                port:
                  number: 5050
          - path: /
            pathType: Prefix
            backend:
              service:
                name: iwas-frontend
                port:
                  number: 80
    - host: www.iwas-capstone.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: iwas-api
                port:
                  number: 5050
          - path: /
            pathType: Prefix
            backend:
              service:
                name: iwas-frontend
                port:
                  number: 80
