apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iwas-ingress
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          # API: anything starting with /api goes to Flask
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: iwas-api
                port:
                  number: 5000

          # Frontend SPA: everything else goes to React
          - path: /
            pathType: Prefix
            backend:
              service:
                name: iwas-frontend
                port:
                  number: 80
