apiVersion: v1
kind: Secret
metadata:
  name: iwas-secret
type: Opaque
stringData:
  SECRET_KEY: "dev-secret-change-me"
  JWT_SECRET_KEY: "1758f2f647873a6bbc138403d11fc90b"
  INTEGRATION_KEY: "-vuaWgUUjFT8PCBGVxQFZipPfvaZEp7-msxNf0FKORc="
