apiVersion: v1
kind: Secret
metadata:
  name: iwas-secret
type: Opaque
data:
  SECRET_KEY: ZGV2LXNlY3JldC1jaGFuZ2UtbWU=      # base64 of dev-secret-change-me
  JWT_SECRET_KEY: MTc1OGYyZjY0Nzg3M2E2YmJjMTM4NDAzZDExZmM5MGI=  # example
  INTEGRATION_KEY: LXYdYVc4VVVqRlQ4UENCZ1Z4UUZWaXJQZnZhWkVwNy1tc3hOZjBG
