# =======================
# MySQL Service
# =======================
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306

# ===================
# Frontend
# ===================
apiVersion: v1
kind: Service
metadata:
  name: iwas-frontend
spec:
  type: LoadBalancer
  selector:
    app: iwas-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80

---
# ===================
# API
# ===================
apiVersion: v1
kind: Service
metadata:
  name: iwas-api
spec:
  type: ClusterIP
  selector:
    app: iwas-api
  ports:
    - port: 5050
      targetPort: 5050
